"""Character lifecycle helpers for the Axiom Engine."""

from engine._core import (
    MEMORY_DECAY_RATE,
    RACE_LIFESPAN,
    _add_memory,
    _advance_age,
    _apply_damage,
    _build_relationship_signals,
    _compute_character_event_pressure,
    _compute_faction_event_pressure,
    _critical_health_death_chance,
    _decay_relationships,
    _drift_relationships_from_power,
    _evolve_relationships,
    _evolve_traits,
    _fade_memories,
    _health_death_modifier,
    _natural_death_chance,
    _parse_age_float,
    _recover_health,
    _relationship_decision_weights,
    _seed_relationship,
    _seed_relationships_for,
    _trait_evolution_rate,
)

__all__ = [
    "RACE_LIFESPAN",
    "MEMORY_DECAY_RATE",
    "_parse_age_float",
    "_advance_age",
    "_natural_death_chance",
    "_apply_damage",
    "_recover_health",
    "_health_death_modifier",
    "_critical_health_death_chance",
    "_add_memory",
    "_fade_memories",
    "_trait_evolution_rate",
    "_evolve_traits",
    "_seed_relationship",
    "_seed_relationships_for",
    "_evolve_relationships",
    "_drift_relationships_from_power",
    "_decay_relationships",
    "_relationship_decision_weights",
    "_build_relationship_signals",
    "_compute_character_event_pressure",
    "_compute_faction_event_pressure",
]
