/**
 * AUTO-GENERATED by scripts/generate-lore-house-map.mjs — do not edit by hand.
 * Run: node scripts/generate-lore-house-map.mjs
 * One province per named house/clan from app.py _PERMANENT_HOUSES (+ Stonebreak hold).
 */
import type { RegionDefinition } from './regions';

export const regionsLoreHouses: RegionDefinition[] = [
  {
    "id": "frostvale__adkison",
    "name": "House Adkison",
    "description": "House Adkison — holding within Wintermark (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        516,
        120.8
      ],
      [
        500,
        220
      ],
      [
        360,
        140
      ]
    ]
  },
  {
    "id": "frostvale__mcintosh",
    "name": "House McIntosh",
    "description": "House McIntosh — holding within Wintermark (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        400,
        24
      ],
      [
        640,
        20
      ],
      [
        680,
        200
      ],
      [
        500,
        220
      ],
      [
        360,
        140
      ]
    ]
  },
  {
    "id": "frostvale__holter",
    "name": "House Holter",
    "description": "House Holter — holding within Wintermark (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        400,
        24
      ],
      [
        640,
        20
      ],
      [
        680,
        200
      ],
      [
        500,
        220
      ],
      [
        360,
        140
      ]
    ]
  },
  {
    "id": "frostvale__duval",
    "name": "House Duval",
    "description": "House Duval — holding within Wintermark (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        400,
        24
      ],
      [
        640,
        20
      ],
      [
        680,
        200
      ],
      [
        500,
        220
      ],
      [
        360,
        140
      ]
    ]
  },
  {
    "id": "faerwood__verlorn",
    "name": "House Verlorn",
    "description": "House Verlorn — holding within Faerwood (Shadow Court) (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        218.66666666666666,
        261.3333333333333
      ],
      [
        40,
        260
      ],
      [
        32,
        96
      ]
    ]
  },
  {
    "id": "faerwood__nightborn",
    "name": "House Nightborn",
    "description": "House Nightborn — holding within Faerwood (Shadow Court) (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        218.66666666666666,
        261.3333333333333
      ],
      [
        380,
        72
      ],
      [
        440,
        300
      ]
    ]
  },
  {
    "id": "faerwood__shadowveil",
    "name": "House Shadowveil",
    "description": "House Shadowveil — holding within Faerwood (Shadow Court) (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        218.66666666666666,
        261.3333333333333
      ],
      [
        300,
        440
      ],
      [
        120,
        400
      ]
    ]
  },
  {
    "id": "glenhaven__wood",
    "name": "House Wood",
    "description": "House Wood — holding within Glenhaven (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        121.6,
        440
      ],
      [
        220,
        280
      ],
      [
        280,
        540
      ]
    ]
  },
  {
    "id": "glenhaven__darkleaf",
    "name": "House Darkleaf",
    "description": "House Darkleaf — holding within Glenhaven (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        121.6,
        440
      ],
      [
        72,
        600
      ],
      [
        20,
        480
      ]
    ]
  },
  {
    "id": "glenhaven__mistafae",
    "name": "House Mistafae",
    "description": "House Mistafae — holding within Glenhaven (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        16,
        300
      ],
      [
        220,
        280
      ],
      [
        280,
        540
      ],
      [
        72,
        600
      ],
      [
        20,
        480
      ]
    ]
  },
  {
    "id": "lostfeld__goldfinger-duke",
    "name": "Clan Goldfinger-Duke",
    "description": "Clan Goldfinger-Duke — holding within Lostfeld (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        380,
        400
      ],
      [
        480,
        280
      ],
      [
        520,
        480
      ]
    ]
  },
  {
    "id": "lostfeld__runewarden",
    "name": "Clan Runewarden",
    "description": "Clan Runewarden — holding within Lostfeld (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        380,
        400
      ],
      [
        360,
        520
      ],
      [
        260,
        420
      ]
    ]
  },
  {
    "id": "lostfeld__ironmaul",
    "name": "Clan Ironmaul",
    "description": "Clan Ironmaul — holding within Lostfeld (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        280,
        300
      ],
      [
        480,
        280
      ],
      [
        520,
        480
      ],
      [
        360,
        520
      ],
      [
        260,
        420
      ]
    ]
  },
  {
    "id": "stonebreak__monastery",
    "name": "Stonebreak Monastery",
    "description": "Stonebreak Monastery — holding within Stonebreak (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        320,
        400
      ],
      [
        420,
        384
      ],
      [
        448,
        480
      ],
      [
        360,
        508
      ],
      [
        300,
        456
      ]
    ]
  },
  {
    "id": "eresteron__aurand",
    "name": "House Aurand",
    "description": "House Aurand — holding within Eresteron (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        544.8,
        444
      ],
      [
        620,
        344
      ],
      [
        656,
        500
      ]
    ]
  },
  {
    "id": "eresteron__braafhart",
    "name": "House Braafhart",
    "description": "House Braafhart — holding within Eresteron (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        544.8,
        444
      ],
      [
        520,
        544
      ],
      [
        448,
        472
      ]
    ]
  },
  {
    "id": "eresteron__bower",
    "name": "House Bower",
    "description": "House Bower — holding within Eresteron (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        480,
        360
      ],
      [
        620,
        344
      ],
      [
        656,
        500
      ],
      [
        520,
        544
      ],
      [
        448,
        472
      ]
    ]
  },
  {
    "id": "eldoria__lefleur",
    "name": "House LeFleur",
    "description": "House LeFleur — holding within Eldoria (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        716,
        460.8
      ],
      [
        800,
        392
      ],
      [
        824,
        520
      ]
    ]
  },
  {
    "id": "eldoria__binx",
    "name": "House Binx",
    "description": "House Binx — holding within Eldoria (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        716,
        460.8
      ],
      [
        700,
        552
      ],
      [
        636,
        496
      ]
    ]
  },
  {
    "id": "eldoria__dale",
    "name": "House Dale",
    "description": "House Dale — holding within Eldoria (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        620,
        344
      ],
      [
        800,
        392
      ],
      [
        824,
        520
      ],
      [
        700,
        552
      ],
      [
        636,
        496
      ]
    ]
  },
  {
    "id": "groth__mijid",
    "name": "Clan Mijid",
    "description": "Clan Mijid — holding within Groth (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        840.8,
        152
      ],
      [
        1008,
        48
      ],
      [
        1016,
        240
      ]
    ]
  },
  {
    "id": "groth__ashfang",
    "name": "Clan Ashfang",
    "description": "Clan Ashfang — holding within Groth (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        840.8,
        152
      ],
      [
        800,
        280
      ],
      [
        700,
        160
      ]
    ]
  },
  {
    "id": "groth__syncar",
    "name": "Clan Syncar",
    "description": "Clan Syncar — holding within Groth (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        680,
        32
      ],
      [
        1008,
        48
      ],
      [
        1016,
        240
      ],
      [
        800,
        280
      ],
      [
        700,
        160
      ]
    ]
  },
  {
    "id": "gilgeth__blackblood",
    "name": "Clan Blackblood",
    "description": "Clan Blackblood — holding within Gilgeth (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        857.6,
        392.8
      ],
      [
        760,
        280
      ],
      [
        1000,
        320
      ]
    ]
  },
  {
    "id": "gilgeth__ironhide",
    "name": "Clan Ironhide",
    "description": "Clan Ironhide — holding within Gilgeth (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        857.6,
        392.8
      ],
      [
        980,
        500
      ],
      [
        800,
        484
      ]
    ]
  },
  {
    "id": "gilgeth__redtusk",
    "name": "Clan Redtusk",
    "description": "Clan Redtusk — holding within Gilgeth (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        760,
        280
      ],
      [
        1000,
        320
      ],
      [
        980,
        500
      ],
      [
        800,
        484
      ],
      [
        748,
        380
      ]
    ]
  },
  {
    "id": "dur_khadur__gross",
    "name": "House Gross",
    "description": "House Gross — holding within Dur Khadur (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        768,
        550.4
      ],
      [
        880,
        620
      ],
      [
        700,
        600
      ]
    ]
  },
  {
    "id": "dur_khadur__delonious",
    "name": "House Delonious",
    "description": "House Delonious — holding within Dur Khadur (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        700,
        480
      ],
      [
        900,
        512
      ],
      [
        880,
        620
      ],
      [
        700,
        600
      ],
      [
        660,
        540
      ]
    ]
  },
  {
    "id": "dur_khadur__galfazzar",
    "name": "House Galfazzar",
    "description": "House Galfazzar — holding within Dur Khadur (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        700,
        480
      ],
      [
        900,
        512
      ],
      [
        880,
        620
      ],
      [
        700,
        600
      ],
      [
        660,
        540
      ]
    ]
  },
  {
    "id": "dur_khadur__vercenti",
    "name": "House Vercenti",
    "description": "House Vercenti — holding within Dur Khadur (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        700,
        480
      ],
      [
        900,
        512
      ],
      [
        880,
        620
      ],
      [
        700,
        600
      ],
      [
        660,
        540
      ]
    ]
  },
  {
    "id": "tidefall__ver-meer",
    "name": "House Ver Meer",
    "description": "House Ver Meer — holding within Tidefall (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        496,
        580
      ],
      [
        480,
        672
      ],
      [
        360,
        600
      ]
    ]
  },
  {
    "id": "tidefall__highland-dusken",
    "name": "House Highland-Dusken",
    "description": "House Highland-Dusken — holding within Tidefall (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        360,
        500
      ],
      [
        580,
        488
      ],
      [
        700,
        640
      ],
      [
        480,
        672
      ],
      [
        360,
        600
      ]
    ]
  },
  {
    "id": "tidefall__fish",
    "name": "House Fish",
    "description": "House Fish — holding within Tidefall (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        360,
        500
      ],
      [
        580,
        488
      ],
      [
        700,
        640
      ],
      [
        480,
        672
      ],
      [
        360,
        600
      ]
    ]
  },
  {
    "id": "tidefall__mcgowan",
    "name": "House McGowan",
    "description": "House McGowan — holding within Tidefall (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        360,
        500
      ],
      [
        580,
        488
      ],
      [
        700,
        640
      ],
      [
        480,
        672
      ],
      [
        360,
        600
      ]
    ]
  },
  {
    "id": "farrock__van-cleave",
    "name": "House Van Cleave",
    "description": "House Van Cleave — holding within Varkuun (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        500,
        520
      ],
      [
        620,
        500
      ],
      [
        660,
        620
      ],
      [
        540,
        656
      ],
      [
        480,
        580
      ]
    ]
  },
  {
    "id": "vilefin__bloodware",
    "name": "Clan Bloodware",
    "description": "Clan Bloodware — holding within Vilefin (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        854,
        594
      ],
      [
        1008,
        660
      ],
      [
        720,
        676
      ]
    ]
  },
  {
    "id": "vilefin__cogtooth",
    "name": "Clan Cogtooth",
    "description": "Clan Cogtooth — holding within Vilefin (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        680,
        540
      ],
      [
        1008,
        500
      ],
      [
        1008,
        660
      ],
      [
        720,
        676
      ]
    ]
  },
  {
    "id": "vilefin__rustfang",
    "name": "Clan Rustfang",
    "description": "Clan Rustfang — holding within Vilefin (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        680,
        540
      ],
      [
        1008,
        500
      ],
      [
        1008,
        660
      ],
      [
        720,
        676
      ]
    ]
  },
  {
    "id": "dreadwind_isles__blacktide",
    "name": "House Blacktide",
    "description": "House Blacktide — holding within Dreadwind Isles (generated layout; replace with painted basemap when ready).",
    "coordinates": [
      [
        860,
        180
      ],
      [
        1000,
        160
      ],
      [
        1004,
        400
      ],
      [
        900,
        420
      ]
    ]
  }
];
